[package]
name = "vapor"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
colored = "3.0.0"
rust-i18n = "3.1.4"
phf = { version = "0.11.3", features = ["macros"], default-features = false }
lazy_static = "1.5.0"